# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.4
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/home/opt/Vivado_HLS/2016.4/../../Vivado/2016.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcku115-flvf1924-2-e ../xilinx_com_hls_example_1_0.zip
