-include ${COMMON_DIR}/sim/module/ddr4/rtl/ip_top
-include ${COMMON_DIR}/sim/module/ddr4/rtl/cal
-include ${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/map

${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/phy/ddr4_phy_v2_1_xiphy_behav.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/phy/ddr4_phy_v2_1_xiphy.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/iob/ddr4_phy_v2_1_iob_byte.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/iob/ddr4_phy_v2_1_iob.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/clocking/ddr4_phy_v2_1_pll.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_1_xiphy_tristate_wrapper.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_1_xiphy_riuor_wrapper.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_1_xiphy_control_wrapper.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_1_xiphy_byte_wrapper.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_1_xiphy_bitslice_wrapper.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/phy/ddr4_0_phy_ddr4.sv
${COMMON_DIR}/sim/module/ddr4/ip_1/rtl/ip_top/ddr4_0_phy.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_wtr.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ref.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_rd_wr.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_periodic.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_group.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ecc_merge_enc.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ecc_gen.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ecc_fi_xor.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ecc_dec_fix.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ecc_buf.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ecc.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_ctl.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_cmd_mux_c.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_cmd_mux_ap.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_arb_p.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_arb_mux_p.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_arb_c.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_arb_a.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_act_timer.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc_act_rank.sv
${COMMON_DIR}/sim/module/ddr4/rtl/controller/ddr4_v2_1_mc.sv
${COMMON_DIR}/sim/module/ddr4/rtl/ui/ddr4_v2_1_ui_wr_data.sv
${COMMON_DIR}/sim/module/ddr4/rtl/ui/ddr4_v2_1_ui_rd_data.sv
${COMMON_DIR}/sim/module/ddr4/rtl/ui/ddr4_v2_1_ui_cmd.sv
${COMMON_DIR}/sim/module/ddr4/rtl/ui/ddr4_v2_1_ui.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_ar_channel.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_aw_channel.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_b_channel.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_cmd_arbiter.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_cmd_fsm.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_cmd_translator.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_fifo.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_incr_cmd.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_r_channel.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_w_channel.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_wr_cmd_fsm.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_wrap_cmd.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_a_upsizer.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_register_slice.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axi_upsizer.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_axic_register_slice.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_carry_and.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_carry_latch_and.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_carry_latch_or.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_carry_or.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_command_fifo.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_comparator.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_comparator_sel.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_comparator_sel_static.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_r_upsizer.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi/ddr4_v2_1_w_upsizer.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi_ctrl/ddr4_v2_1_axi_ctrl_addr_decode.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi_ctrl/ddr4_v2_1_axi_ctrl_read.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi_ctrl/ddr4_v2_1_axi_ctrl_reg_bank.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi_ctrl/ddr4_v2_1_axi_ctrl_reg.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi_ctrl/ddr4_v2_1_axi_ctrl_top.sv
${COMMON_DIR}/sim/module/ddr4/rtl/axi_ctrl/ddr4_v2_1_axi_ctrl_write.sv
${COMMON_DIR}/sim/module/ddr4/rtl/clocking/ddr4_v2_1_infrastructure.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_xsdb_bram.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_write.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_wr_byte.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_wr_bit.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_sync.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_0_ddr4_cal_riu.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_read.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_rd_en.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_pi.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_mc_odt.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_debug_microblaze.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_cplx_data.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_cplx.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_config_rom.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_addr_decode.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_top.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal_xsdb_arbiter.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_cal.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_chipscope_xsdb_slave.sv
${COMMON_DIR}/sim/module/ddr4/rtl/cal/ddr4_v2_1_dp_AB9.sv
#${COMMON_DIR}/sim/module/ddr4/rtl/ip_top/ddr4_0.sv
#${COMMON_DIR}/sim/module/ddr4/rtl/ip_top/ddr4_0_ddr4.sv
${COMMON_DIR}/sim/module/ddr4/rtl/ip_top/ddr4_0_ddr4_mem_intfc.sv
${COMMON_DIR}/sim/module/ddr4/tb/microblaze_mcs_0.sv
#${COMMON_DIR}/sim/module/ddr4/ip_0/sim/ddr4_0_microblaze_mcs.v

--include ${COMMON_DIR}/sim/module/dram_model
--sourcelibdir ${COMMON_DIR}/sim/module/dram_model

${COMMON_DIR}/sim/module/dram_model/ddr4_sdram_model_wrapper.sv
${COMMON_DIR}/sim/module/dram_model/dram_wrapper.sv
